### ISSUE TITLE
Issue with Creating a go2cs Executable to Convert my Golang Code

### ISSUE THREAD

**Issue by BGcoder321** [GridProtectionAlliance/go2cs#12]
Hello @ritchiecarroll,

I have been struggling with trying to convert my go code using this go2cs converter. I attempted to run the deploy-gocore.bat script but am unsure where the go executable is located once I complete this script or if I am missing a step in creating the go2cs executable. Also, does it matter if my go2cs code is located in the go directory where the golang is stored on my PC or can it be in a separate directory on my local drive.

**Comment by ritchiecarroll** [comment]
I generally build with Visual Studio - can test within that environment as well. Are you trying to build from command prompt?

**Comment by BGcoder321** [comment]
Hi @ritchiecarroll , 
yeah I was attempting to build in the cmd prompt as I wasn't exactly sure where the README.txt wanted me to build it at. I will try rebuilding the go2cs.exe in visual studio.

**Comment by ritchiecarroll** [comment]
Pre-compiled version now available: https://github.com/GridProtectionAlliance/go2cs/releases/
