### ISSUE TITLE
Unix path seperator

### ISSUE THREAD

**Issue by Stovoy** [GridProtectionAlliance/go2cs#14]
Hi, great project!

I have a full unix-workflow and so was trying to get this working end-to-end in unix, through Docker.

I finally got it working, but it required some patches:

`cd go2cs/src/go2cs/ScannerBase && sed 's/"\\\\"/Char.ToString(Path.DirectorySeparatorChar)/g' ScannerBase.cs`
`cd go2cs/src/go2cs && sed 's#\\\\#/#g' Options.cs` (This one could be changed to use Path.DirectorySeparatorChar too)

Without these changes, it didn't work properly, since Unix uses exclusively forward slashes for the path, and it was not finding the files or outputting properly.

**Comment by ritchiecarroll** [comment]
Thanks for the heads up / fixes - haven't even tried testing from Linux environment yet - so not surprised that this gave you some hiccups. 

I'll get your changes incorporated.
