### ISSUE TITLE
error MSB4025: The project file could not be loaded

### ISSUE THREAD

**Issue by SinanovicEdis** [GridProtectionAlliance/go2cs#15]
Hi everyone, 

I have an Issue when i run deploy-gocore.bat. 

error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.

I am very thankful for all the help. 
Best regards!

**Comment by ritchiecarroll** [comment]
What is the value of `%GOPATH%` on your command line? For example, mine is `C:\Users\ritchie\go`

Also, I would run this batch file from a command line in the same folder that is located.

Thanks!
Ritchie

**Comment by ritchiecarroll** [comment]
A compiled version is now available for testing: https://github.com/GridProtectionAlliance/go2cs/releases/
