### ISSUE TITLE
Experimental Release go2cs.exe file not worked.

### ISSUE THREAD

**Issue by theolovesyou** [GridProtectionAlliance/go2cs#19]
I move go2cs.exe to bin folder
and extract dependencies.zip to src folder.
and when i run go2cs.exe,
the console window showed up and closed immediately.
nothing showed up.
is there something i missed?

**Comment by ritchiecarroll** [comment]
Did you try this release version?
https://github.com/GridProtectionAlliance/go2cs/releases/tag/v0.1.2

**Comment by ritchiecarroll** [comment]
Also, please provide platform details, e.g., Linux, Windows, etc.

**Comment by theoburp** [comment]
yes i used v0.1.2 again, but it was same.
and i use windows 10 64 bit.
