### ISSUE TITLE
Documentation oopsie

### ISSUE THREAD

**Issue by hitchhiker** [GridProtectionAlliance/go2cs#4]
Hey, interesting project - just had to point out that "human-readable byte-code" is a contradiction in terms though.

**Comment by ritchiecarroll** [comment]
Thanks. How about "simple to interpret byte-code"

**Comment by hitchhiker** [comment]
Simple to JIT but hardly simple for any human being to interpret:
> .maxstack 2
    ldarg.0
    ldarg.1
    add
    ldarg.2
    add
    ldarg.3
    add
    ldarg.s e
    add
    ldc.i4 1024
    mul
    ret

I think what you mean to convey is that the generated CIL is efficiently converted at runtime to platform specific code.

**Comment by ritchiecarroll** [comment]
Updated: https://github.com/GridProtectionAlliance/go2cs/blob/master/README.md
