### ISSUE TITLE
Linux installation

### ISSUE THREAD

**Issue by 0pcom** [GridProtectionAlliance/go2cs#5]
Hi, I was eager to see what go2cs can do on linux. The installation section of the readme references `go2cs.exe`but I can't find that anywhere in the repo or the release section, or information on source compilation.

**Comment by ritchiecarroll** [comment]
My goal is to full convert this project to .NET Core for full cross platform support. This is a pet project for me, so my investment time is limited.

I'll try to keep you posted.

Thanks,
Ritchie

**Comment by ritchiecarroll** [comment]
BTW, fully on .NET core version 5 now, should be able to test Linux without issue.
