### ISSUE TITLE
Alternative strategy for "Inline Assignment Order of Operations"

### ISSUE THREAD

**Issue by ebekker** [GridProtectionAlliance/go2cs#6]
For [this](https://go2cs.net/ConversionStrategies.html#inline-assignment-order-of-operations) strategy, a roughly equivalent and simpler C# form is to make use of tuples on both sides of the assignment.

In your example:
```go
x, y = y, x+y
```
a comparable C# equivalent would be
```c#
(x, y) = (y, x+y)
```

**Comment by ritchiecarroll** [comment]
Does that work ? Awesome. Wow - I learn something everyday!

**Comment by ritchiecarroll** [comment]
Works great:

https://play.golang.org/p/bOhOvo1s846 => https://dotnetfiddle.net/HfIpjz
