### ISSUE TITLE
Сonvert error

### ISSUE THREAD

**Issue by IlyaKrav** [GridProtectionAlliance/go2cs#7]
I can't convert go file to C# with error at screenshot. Please help! What I do wrong?
![Screenshot_1](https://user-images.githubusercontent.com/35541202/107032568-1a285080-67c5-11eb-9bb9-7f0fca79a77e.png)

**Comment by ritchiecarroll** [comment]
Can you provide the Go source file?

**Comment by creatio** [comment]
@ritchiecarroll I receive the same error while trying to convert the following file: `https://github.com/ory/keto/blob/master/internal/relationtuple/definitions.go`

**Comment by ritchiecarroll** [comment]
Thanks for the source file and the debugging - should be relatively easy to fix.
