### ISSUE TITLE
How does it compare to RemObject universal Elements compiler? It can compile GO syntax to .NET bytecode

### ISSUE THREAD

**Issue by aprokopyev** [GridProtectionAlliance/go2cs#9]
Hello,

Please let me know, if I am interested only in using ready open source GO libraries then is there any difference in using your tool and RemObjects GOLD ? So I need to reference these GO libraries from my .NET program and then run it on .NET runtime.

https://docs.elementscompiler.com/Gold/

It seems there is less activity in your project development now?

**Comment by ritchiecarroll** [comment]
Yes, I've been busy with other priorities so I've not been active on this project for a while. Hoping to get back to it soon.

Haven't seen RemObject GOLD before, that said it looks like a way to use the Go language to support development against their toolset, not a source code converter - i.e., more of an integration tool for their tools.

**Comment by ritchiecarroll** [comment]
Please feel to compare with released version: https://github.com/GridProtectionAlliance/go2cs/releases/

FYI, code is converted to native C# which does compile to .NET bytecode.
